Adding Ribodesigner
sequana/sequana pull request #708
Opened 2021-12-08 14:57 UTC by khourhin

2021-12-09 09:11 UTC, ddesvillechabrol commented on test/test_ribodesigner.py
> +    shutil.copytree(resources_dir, tmpdir, dirs_exist_ok=True)
D'après la doc, le paramètre `dirs_exist_ok` a été ajouté a partir de python 3.8 c'est pour ça que les tests sur 3.7 ne passent pas.

2021-12-09 09:28 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +    return rev_comp_sequence
Il y a l'objet `Sequence` dans la lib qui te permet de faire ça.
`Sequence(sequence).get_complement()`

2021-12-09 09:32 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +        with open(fasta_out, "w") as fas_out:
Tu peux one line ces deux `with` si tu veux économiser une indentation

2021-12-09 09:35 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +                seq_record = f">{rna['seqid']}:{rna['start']}-{rna['end']}\n{fas.fetch(region=region)}\n"
C'est important d'avoir indexé le fichier fasta sinon le fetch va être lent voir te retourné une erreur non ?

2021-12-09 09:38 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +                count += 1
Au final ton count c'est la longueur de ton df à priori

2021-12-09 09:48 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +    cmd = f"cd-hit-est -i {fasta_in} -o {fasta_out} -c {seq_id_thres} -n {threads}"
On gère nul part la présence ou non de ce programme a priori, faudrait au moins une erreur clair pour savoir qu'il manque un executable

2021-12-09 09:51 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +            seq_dict["sequence"].append(seq.sequence)
Tu peux juste faire une liste de tuple en liste comprehension pour le donner à manger à DataFrame il me semble.
Ce sera plus élégant

2021-12-09 09:52 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +            seq_dict["sequence"].append(seq.sequence)
Voir même juste un générator comme ça on parcours qu'une fois les données 😄

2021-12-09 09:56 UTC, ddesvillechabrol commented on test/test_ribodesigner.py
> +            assert list(f1) == list(f2)
Tu peux utiliser `filecmp.cmp`

2021-12-09 09:58 UTC, ddesvillechabrol reviewed
Noice ! J'ai quelque petits trucs dont je suis pas le publique.
Et vous voulez pas split votre mega fichier main qui fait 1400 lignes bientôt ? xD

2021-12-09 09:58 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +    cmd = f"cd-hit-est -i {fasta_in} -o {fasta_out} -c {seq_id_thres} -n {threads}"
Je pense que les tests passent pas parce qu'il n'y a pas l'exécutable d'installé dans le github action

2021-12-09 11:53 UTC, cokelaer commented on sequana/ribodesigner.py
> +"""Ribodesigner module"""
copy/paster header de e.g. fastq.py

2021-12-09 11:54 UTC, cokelaer commented on sequana/ribodesigner.py
> +import sys
import pythonlib en premier, espace puis import lib extern (pysam/pandas), puis sequana

2021-12-09 12:01 UTC, cokelaer commented on sequana/ribodesigner.py
> +    return rev_comp_sequence
je confirme.

2021-12-09 12:15 UTC, cokelaer commented on sequana/ribodesigner.py
> +    df = pd.read_csv(
Il faudrait peut etre voir à réutiliser GGF3
Pour du bacterien c'est pas grave mais pour du eukaryotes, on veut peut etre utiliser GGF3

    from sequana.gff3 import GFF3
    g = GFF3(...)

tu peux par exemple extraire les rRNA et relire:

   g:save_gff_filtered(filename="filtered.gff", features=['rRNA'])
   df = GFF3("filtered.gff").df

2021-12-09 12:18 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +import sys
Sinon tu peux utiliser isort pour trier 😄
https://github.com/PyCQA/isort

2021-12-09 12:18 UTC, ddesvillechabrol commented on sequana/ribodesigner.py
> +    return rev_comp_sequence
Aie aie 2 manières de faire différentes dans une lib, c'est pas bien ça 😛

2021-12-09 12:18 UTC, cokelaer commented on sequana/ribodesigner.py
> +def extract_regions_from_fasta(fasta_in, regions_df, fasta_out):
Cette fonction pourrait etre intégrer à la class GGF3 au final.
Y a déjà la méthode to_bed, et on pourrait ajouter to_fasta

2021-12-09 12:22 UTC, cokelaer commented on sequana/ribodesigner.py
> +    """From a FASTA file of nucleotide sequence to be targetted, generate a FASTA
du détail; pour la doc une petite phrase résumé, une ligne vide puis le détails. C'est mieux pour sphinx

2021-12-09 12:31 UTC, cokelaer commented on sequana/ribodesigner.py
> +    cmd = f"cd-hit-est -i {fasta_in} -o {fasta_out} -c {seq_id_thres} -n {threads}"
oui, on pourra tester la présence de cd-hit-est ici ou à l'appel dans la commande

    sequana ribodesigner

2021-12-09 12:31 UTC, cokelaer commented on sequana/ribodesigner.py
> +    """Convert a FASTA file into a CSV file with the oligo name in column 1 and the
Convert a FASTA file into a CSV file 

The the oligo name in column 1 and the oligo sequence in column 2

2021-12-09 13:09 UTC, cokelaer commented on sequana/scripts/main.py
> +@click.option("--outdir", default="out_ribodesigner", type=click.Path(exists=False))
Je suis pas sur d'etre cohérent moi meme, mais pour uniformiser, on va utiliser      "--output-directory" au lieu de --outdir

2021-12-09 13:09 UTC, cokelaer commented on sequana/scripts/main.py
> +@click.option("--seq_type", default="rRNA", help="The annotation type (column 3 in gff) to target for probes.")
--seq-type bien que je crois que ça ne change rien car click transforme le _ en -

2021-12-09 13:10 UTC, cokelaer commented on sequana/scripts/main.py
> +    """A tool to design custom ribodepletion probes, using a reference genome (FASTA file) and the corresponding annotation (GFF file). CD-HIT-EST should be installed and in your $PATH."""
Ici, a noter que 

sequana --help ne montr que les premiers 80 charactere donc pareil que pour les docstrings, d'abord une petit phrase, on passe une ligne vide et après le détails

2021-12-09 13:10 UTC, cokelaer commented on sequana/scripts/main.py
> +    outdir.mkdir()
si ça existe, ça fonctionne ?

2021-12-09 13:11 UTC, cokelaer commented on sequana/scripts/main.py
> +    # logger.info("test")
on peut supprmier le logger du coup

2021-12-09 13:12 UTC, cokelaer commented on sequana/scripts/main.py
> +    df = rd.get_rna_pos_from_gff(kwargs["gff"], seq_type=kwargs["seq_type"])
la var rd est pas défini ? ou je me trompe ?
On pourrait faire une class RiboDesigner dans le le module sequana.ribofinder au final ça sera plus simple peut etre

2021-12-09 13:12 UTC, ddesvillechabrol commented on sequana/scripts/main.py
> +    outdir.mkdir()
Il manque le `exist_ok=True` 😄

2021-12-09 13:14 UTC, cokelaer commented on test/test_ribodesigner.py
> +#!/usr/bin/env python
pas la peine le /usr/bin/env

2021-12-09 13:15 UTC, cokelaer commented on test/test_ribodesigner.py
> +            assert list(f1) == list(f2)
ou filecmp.dirdiff

2021-12-09 13:16 UTC, cokelaer commented on test/test_ribodesigner.py
> +def test_reverse_complement():
du coup si tu tulises sequana.tools.reverse_complement, déjà testé ... je crois :-)

2021-12-09 13:18 UTC, cokelaer requested changes
Cool !! qqs changements sur le reverse_complement à réutiliser, peut etre inclure le extrqct_fasta dans la class GFF et faire une class RiboDesigner. Hésite pas à demander si pas clair. merci

2022-01-06 15:42 UTC, cokelaer commented on sequana/ribodesigner.py
> +# -*- coding: utf-8 -*-
on enlève cette ligne (utf-8) maintenant

2022-01-06 15:43 UTC, cokelaer commented on sequana/ribodesigner.py
> +#  File author(s):
et les auteurs (sequana development team suffit)

2022-01-06 15:43 UTC, cokelaer commented on sequana/ribodesigner.py
> +    select rRNA from.
une tabulation sinon la doc sphinx va raller

2022-01-06 15:46 UTC, cokelaer commented on sequana/scripts/main.py
> +    print(kwargs)
reste un print ici

2022-01-06 15:47 UTC, cokelaer approved these changes

2022-01-06 15:47 UTC, ddesvillechabrol commented on sequana/scripts/main.py
> +    if cmd_exists("cd-hit-est") is False:
`if not`

2022-01-06 15:50 UTC, ddesvillechabrol commented on sequana/scripts/main.py
> +        "a valid KEGG name (hsa for human, mmu for mus musculus);  " "See the taxonomy command to retrieved other names"
Black a fait un truc chelou ici

2022-01-06 15:51 UTC, ddesvillechabrol approved these changes

2022-01-06 16:08 UTC, merged